config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  resources :static_pages
  resources :events, only: [:index, :new, :create, :show] do
    post 'register', on: :member
  end
  
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  resources :users, only:[:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "events#index"

  #STRIPE

  #root 'orders#new'
  resources :orders, only: [:new, :create]

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event
  belongs_to :user


  after_create :send_alert_to_admin

  private

  def send_alert_to_admin
    if event.present? && event.admin.present?
      admin = event.admin
      UserMailer.attendance_alert(admin, user).deliver_now
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin, class_name: "User"
  has_many :attendances
  has_many :users, through: :attendances
 
  validates :start_date, presence: true
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :multiple_of_five
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price,  presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
  validates :location, presence: true


  def end_date
    start_date + duration.hours
  end


  private

  def multiple_of_five
    if duration.present? && duration % 5 != 0
      errors.add(:duration, "doit être un multiple de 5")
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attendances
  has_many :events, through: :attendances
  
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  # Définir une méthode pour obtenir le nom complet de l'utilisateur
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_parameters, if: :devise_controller?

    def configure_devise_parameters
        devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
        devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
    end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  

  def create
    @total = params[:total].to_d
    @event_id = params[:event_id]
    
    # Vérifier que les paramètres sont correctement extraits
    # puts "Total: #{@total}"
    # puts "Event ID: #{@event_id}"
  
    @session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'eur',
            unit_amount: (@total * 100).to_i,
            product_data: {
              name: 'Rails Stripe Checkout',
            },
          },
          quantity: 1
        }
      ],
      metadata: {
        event_id: params[:event_id]
      },
      mode: 'payment',
      success_url: checkout_success_url + '?session_id={CHECKOUT_SESSION_ID}',
      cancel_url: checkout_cancel_url
    )
  
    redirect_to @session.url, allow_other_host: true
  end


  def success
    session_id = params[:session_id]
    #begin
      @session = Stripe::Checkout::Session.retrieve(session_id)
      @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
      @event_id = @session.metadata.event_id

      # Créer une attendance
      @attendance = Attendance.create(user_id: current_user.id, event_id: @event_id)
      flash[:notice] = "La commande a été validée."

      # Charger l'événement associé au paiement
      @event = Event.find(@event_id)      
      
    # rescue Stripe::InvalidRequestError => e
    #   # Gérer les erreurs, par exemple rediriger l'utilisateur vers une page d'erreur
    #   flash[:error] = "Une erreur est survenue lors de la récupération des informations de paiement."
      
    # end
  end

  def cancel
    # Logique pour l'annulation de la commande
    # Vous pouvez gérer ici les actions à entreprendre en cas d'annulation de paiement
    flash[:notice] = "La commande a été annulée."
    
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :register]

  def index
    @events = Event.all
  end

  def show 
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to events_path, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def register
    @event = Event.find(params[:id])
    @attendance = Attendance.new(user_id: current_user.id, event_id: @event.id)

    if @attendance.save
      redirect_to @event, notice: 'You have successfully registered for the event.'
    else
      redirect_to @event, alert: 'Failed to register for the event.'
    end
  end

  private

  def event_params
    params.require(:event).permit(:admin_id, :title, :start_date, :duration, :description, :price, :location)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def create
    # Before the rescue, at the beginning of the method
    @stripe_amount = 500
  begin
    customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
    })
    charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @stripe_amount,
    description: "Achat d'un produit",
    currency: 'eur',
    })
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_order_path
  end
  # After the rescue, if the payment succeeded
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:secret]
  
  def index
  end

  def secret
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
   before_action :configure_sign_in_params, only: [:create, :destroy]

  # GET /resource/sign_in
   def new
     super
   end

  # POST /resource/sign_in
   def create
     super
   end

  # DELETE /resource/sign_out
  def destroy
    logger.info "Destroy method called"
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @events = Event.all
  end

private

  def user_params
    params.require(:user).permit(:email, :description, :first_name, :last_name, :encrypted_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checkout/cancel.html.erb
<div class="container text-center my-5"> 
    <h1>Echec</h1> 
    <p>Le paiement n'a pas abouti.</p> 
    <%= link_to "retour à l'accueil", root_path, class: "btn btn-primary" %>
</div>

app/views/checkout/new.html.erb
<%= button_to "Passer commande (NEXT GEN)", checkout_create_path(total: MONTANT À PAYER, event_id: ID POUR LA METADATA), class: "btn btn-primary", data: {turbo: false} %>

app/views/checkout/success.html.erb
<div class="container text-center my-5">
    <h1>Succès</h1> 
    <p>Nous avons bien reçu votre paiement de <%= number_to_currency(@payment_intent.amount_received / 100.0, unit: "€", separator: ",", delimiter: "", format: "%n %u") %>.</p>
     <p>Le statut de votre paiement est : <%= @payment_intent.status %>.</p> 
</div>

 <%= link_to "retour à l'événement", event_path(id: @event_id), class: "btn btn-primary" %>

app/views/events/index.html.erb
<!-- Jumbotron -->
<div class="p-5 text-center bg-image rounded-3" style="
    background-image: url('https://mdbcdn.b-cdn.net/img/new/slides/041.webp');
    height: 400px;
  ">
  <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
    <div class="d-flex justify-content-center align-items-center h-100">
      <div class="text-white">
        <h1 class="mb-3">Heading</h1>
        <h4 class="mb-3">Subheading</h4>
        <a class="btn btn-outline-light btn-lg" href="<%= new_event_path %>" role="button">Créer un event</a>
      </div>
    </div>
  </div>
</div>
<!-- Jumbotron -->
<div class="container py-5">
  <div class="row justify-content-center">
    <% @events.sort_by{|e| - e.id}.each do |event| %>
      <div class="col-md-4">
        <!-- Début de l'élément avec les vagues et l'icône -->
        <div class="card box-shadow mx-auto my-5" style="width: 18rem;">
          <!-- Image aléatoire -->
          
          <div class="card-body">
            <!-- Titre du gossip -->
            <h5 class="card-title"><%= event.title %></h5>
            <hr>
            <!-- Auteur du gossip -->
            <% if event.admin %>
              <p class="card-text">Par : <%= event.admin.first_name %></p>
            <% else %>
              <p class="card-text">Par : Anonyme</p>
            <% end %>
            <!-- Contenu du gossip -->
            <p class="card-text"><%= event.description %></p>
            <!-- Bouton Voir plus -->
            <%= link_to "Voir plus", event_path(event), class: "btn btn-primary" %>
          </div>
        </div>
        <!-- Fin de l'élément avec les vagues et l'icône -->
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1>Créer un nouvel événement</h1>

<div class="contact-box p-4 bg-primary">
    <%= form_with(model: @event, url: events_path, method: :post) do |form| %>
        <div class="row">                    
            <div class="col-lg-6">
                <%= form.hidden_field :admin_id, value: current_user.id %>
                <div class="form-group mt-3">
                    <%= form.text_field :title, class: "form-control", placeholder: "Titre" %>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group mt-3">
                    <%= form.time_field :start_date, class: "form-control", placeholder: "Date de début" %>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group mt-3">
                    <%= form.number_field :duration, class: "form-control", placeholder: "Durée (en minutes)" %>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group mt-3">
                    <%= form.text_area :description, class: "form-control", placeholder: "Description" %>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group mt-3">
                    <%= form.text_field :location, class: "form-control", placeholder: "Lieu" %>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group mt-3">
                    <%= form.number_field :price, class: "form-control", placeholder: "Prix" %>
                </div>
            </div>
            <div class="col-lg-12">
                <%= form.submit "Créer l'événement", class: "btn btn-danger mt-3 mb-3 text-white border-0 py-2 px-3" %>
            </div>
        </div>
    <% end %>
</div>

<% if @event && @event.errors.any? %>
    <p>Nous n'avons pas réussi à créer l'événement pour la (ou les) raison(s) suivante(s) :</p>
    <% @event.errors.full_messages.each do |message| %>
        <p class="alert alert-danger" role="alert"><%= message %></p>
    <% end %>
<% end %>

app/views/events/show.html.erb
<div class="col-md-4">
  <div class="card box-shadow mx-auto my-5" style="width: 18rem;">
    <div class="card-body">
      <!-- Titre de l'événement -->
      <h5 class="card-title"><%= @event.title %></h5>
      <hr>
      <!-- Auteur de l'événement -->
      <% if @event.admin %>
        <p class="card-text">Par : <%= @event.admin.first_name %> (<%= @event.admin.email %>)</p>
      <% else %>
        <p class="card-text">Par : Anonyme</p>
      <% end %>
      <!-- Contenu de l'événement -->
      <p class="card-text"><%= @event.description %></p>
      <!-- Nombre d'inscrits à l'événement -->
      <p class="card-text">Nombre d'inscrits : <%= @event.users.count %></p>
      <!-- Date de début de l'événement -->
      <p class="card-text">Date de début : <%= @event.start_date %></p>
      <!-- Date de fin de l'événement -->
      <p class="card-text">Date de fin : <%= @event.end_date %></p>
      <!-- Lieu de l'événement -->
      <p class="card-text">Lieu : <%= @event.location %></p>
      <!-- Prix de l'événement -->
      <p class="card-text">Prix : <%= number_to_currency(@event.price) %></p>

      <%= button_to "S'inscrire à l'Event", checkout_create_path(total: @event.price, event_id: @event.id), class: "btn btn-primary", method: :post, remote: true %>
    </div>
  </div>
</div>
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://js.stripe.com/v3/"></script>
    
  </head>

  <body data-turbo="false">
    <!-- Navigation bar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%=new_user_session_path%>">Eventbrite</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<%=events_path%>">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_event_path %>">Create Event</a>
            </li>
          </ul>
                <% if user_signed_in? %>
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Mon profil
              </a>
              <ul class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="/users/show">Mon profil</a></li>
                  <li><%= button_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
                
              </ul>
            </li>
            <% else %>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
             <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                S'inscrire/ se connecter
              </a>
              <ul class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="<%= new_user_registration_path %>">S'inscrire</a></li>
                  <li><a class="dropdown-item" href="<%= new_user_session_path %>">Se connecter</a></li>
          </ul>
                <% end %>
        </div>
      </div>
    </nav>

    <main>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </main>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>


<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/orders/new.html.erb
<h1>Orders#new</h1>
<p>Find me in app/views/orders/new.html.erb</p>

<%= form_tag orders_path do %>
<article>
  <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <label class="amount">
    <span>Amount: $5.00</span>
  </label>
</article>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Achat d'un produit"
    data-amount="500"
    data-locale="auto">
</script>
<% end %>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>
<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete, data: {turbo_method: :delete} %>
    </li>

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->
<div class="col-md-4">
  <div class="card box-shadow mx-auto my-5" style="width: 18rem;">
    <div class="card-body">
<h1>Profil de <%= @user.first_name %> <%= @user.last_name %></h1>

<p>Prénom : <%= @user.first_name %></p>
<p>Nom de famille : <%= @user.last_name %></p>
<p>Description : <%= @user.description %></p>
<p>E-mail : <%= @user.email %></p>

<h2>Événements créés par <%= @user.first_name %></h2>

<% @events.each do |event| %>
    <% if event.admin == @user %>
    <%= button_to event.title, event_path(event) %>
    
    <% end %>
<% end %>

<% if current_user == @user %>
  <p><%= link_to "Éditer l'e-mail", edit_user_registration_path %></p>
  <p><%= link_to "Éditer le mot de passe", edit_user_registration_path %></p>
<% end %>
    </div>
</div>
</div>